RDKB-52834:Implement Layer 3 WAN testing in wan services
rdkcentral/RdkWanManager pull request #21
Opened 2024-05-17 10:38 UTC by kul2241

Reason for change:Implement Layer 3 WAN testing in wan services Test Procedure:
1.)Test LET bad with Primary good state.
Risks: Medium
Priority: P1
Signed-off-by: kulvendra singh <kulvendra.singh@sky.uk>

2024-05-17 10:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/RdkWanManager?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/RdkWanManager?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/RdkWanManager?pullRequest=21) it.</sub>

2024-05-29 17:12 UTC, S-Parthiban-Selvaraj requested changes

2024-05-30 16:04 UTC, S-Parthiban-Selvaraj requested changes

2024-05-31 16:48 UTC, S-Parthiban-Selvaraj requested changes

2024-06-03 12:19 UTC, kul2241 commented on source/WanManager/wanmgr_sysevents.c
> +            else if (strcmp(name, SYSEVENT_BACKUP_IPV6_DNS) == 0)
added by considering change in value at run time.

2024-06-13 19:29 UTC, guto86 approved these changes

2024-06-18 10:23 UTC, guto86 approved these changes

2024-06-18 13:59 UTC, S-Parthiban-Selvaraj approved these changes

2024-06-18 14:03 UTC, merged