RDKB-55511: Remove RDKB api dependancy from DHCPv4 HAL
rdkcentral/RdkWanManager pull request #24
Opened 2024-05-24 12:29 UTC by AbhishekShivappa

Reason for change: Remove sysevent and implemnt platform api
Test Procedure: No regression in DHCPv4 data model in UI
Risks: Low
Priority: P2

Change-Id: I4da4d800e6014a64182b07ed8293bd9e41cbc7d3

2024-05-28 10:18 UTC, S-Parthiban-Selvaraj commented on source/WanManager/wanmgr_data.c
> +DML_VIRTUAL_IFACE* WanMgr_GetVirtIfData(void)
Please rename to Active Interface Data

2024-05-28 15:35 UTC, S-Parthiban-Selvaraj requested changes

2024-05-29 15:51 UTC, guto86 approved these changes

2024-05-30 17:57 UTC, guto86 approved these changes

2024-05-31 10:38 UTC, S-Parthiban-Selvaraj approved these changes

2024-05-31 12:41 UTC, merged