RDKCOM-4489 RDKBDEV-2282: Support for updating configurable WAN interface to Tele…
rdkcentral/RdkWanManager pull request #65
Opened 2024-09-24 13:19 UTC by sherik-sensin

…covoicemanager

Reason for change:
    - Update configured data interface name to telecovoicemanager.

Test Procedure: Please refer JIRA attachment for detailed test steps
Risks: None

2024-11-04 20:11 UTC, pradeeptakdas commented
Internal ticket for tracking https://ccp.sys.comcast.net/browse/RDKCOM-5137

2025-01-21 15:45 UTC, S-Parthiban-Selvaraj requested changes

2025-01-21 15:45 UTC, S-Parthiban-Selvaraj commented on source/WanManager/wanmgr_interface_sm.c
> +            strncpy(voipIfName, p_VirtIf->Name, sizeof(voipIfName));
Can we remove FEATURE_RDKB_CONFIGURABLE_WAN_INTERFACE check and use p_VirtIf->Name as default ?
p_VirtIf->Name will always have the value.

2025-03-10 13:33 UTC, sherik-sensin commented on source/WanManager/wanmgr_interface_sm.c
> +            strncpy(voipIfName, p_VirtIf->Name, sizeof(voipIfName));
A new PR is raised with the changes. (https://github.com/rdkcentral/RdkWanManager/pull/110/files).
Closing this PR.

2025-03-10 13:33 UTC, closed without merging