RDKBACCL-275 :  Banana Pi R4 integration
rdkcentral/RdkWanManager pull request #68
Opened 2024-10-09 14:50 UTC by anatar818

…ific flags

Reason for change : Changes for Rdk-wan manager for BananaPi R4
Test Procedure: Build and flash the image.erouter0 should get ip
Risks: None

2024-10-10 22:23 UTC, cpokuru commented on source/WanManager/wanmgr_main.c
> +#if defined (_HUB4_PRODUCT_REQ_) || defined(_PLATFORM_BANANAPI_R4_)
pls check here

2024-10-14 19:16 UTC, cpokuru reviewed
Verified wan ipv4/v6.Need augusto review

2024-10-15 11:16 UTC, guto86 requested changes
We will not merge platform unless it's need.
As discussed last time, it was requested for use the generic code instead.

2024-10-15 15:16 UTC, cpokuru commented
Based on augusto suggestion we need to align with XB7 device flow

2025-01-22 15:24 UTC, guto86 commented
Based on previous meetings, we gonna configure RPI4 with the feature flags need.

2025-01-22 15:24 UTC, closed without merging