RDKB-57495: XDNS DM implementation
rdkcentral/RdkWanManager pull request #76
Opened 2024-10-30 09:07 UTC by KavyaShivalingaiah

Reason for change: Implement DM to notify DNS changes to XDNS

Test Procedure:
Updated in Jira.

Risks: none
Priority: P1

2024-10-30 11:38 UTC, S-Parthiban-Selvaraj requested changes

2024-10-30 11:38 UTC, S-Parthiban-Selvaraj commented on source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.h
> +    CHAR    CurrentActiveDNS[BUFLEN_256];
IFACE_INFO linked list was initially added to handle multiple interfaces AvailableStatus in a sorted order. 
CurrentActiveDNS will be needed only for an active interface. Should we require it in the linked list?

2024-10-30 11:38 UTC, S-Parthiban-Selvaraj commented on source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
> +        WanMgr_Rbus_String_EventPublish_OnValueChange(WANMGR_CONFIG_WAN_CURRENTACTIVEDNS, prevCurrentActiveDNS, CurrentActiveDNS);
Is the OLD value required in the publish?

2024-11-07 14:43 UTC, S-Parthiban-Selvaraj requested changes

2024-11-07 14:43 UTC, S-Parthiban-Selvaraj commented on source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
> +        return RETURN_ERR;
The function has void return type.

2024-11-07 14:43 UTC, S-Parthiban-Selvaraj commented on source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
> +        if(strcmp(pWanDmlData->CurrentActiveDNS,CurrentActiveDNS) != 0)
Check for empty CurrentActiveDNS. Update_Current_ActiveDNSmay fail to open the dns conf and return empty string

2024-11-07 14:43 UTC, S-Parthiban-Selvaraj commented on source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
> +            publishCurrentActiveDNS = TRUE;
Directly publish here. 
publishCurrentActiveDNS is not necessary.

2024-11-07 14:43 UTC, S-Parthiban-Selvaraj commented on source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
> +	if(!strcmp(token,"nameserver"))
Please fix the indentation

2024-11-07 14:43 UTC, S-Parthiban-Selvaraj commented on source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
> +        memset(token,0,sizeof(token));
the token is a char pointer. memset is necessary?

2024-11-08 10:24 UTC, S-Parthiban-Selvaraj approved these changes

2024-11-08 15:35 UTC, guto86 approved these changes

2024-11-11 11:16 UTC, merged